"""
UMACAD - Task Planning Data Structures
Project Manager's strategic plan representation
"""

from pydantic import BaseModel, Field, field_validator
from typing import Union, List, Dict, Optional, Any
from enum import Enum
from datetime import datetime
# Note: Ensure '.' is correct relative import, otherwise use 'core.design_brief'
from .design_brief import DesignBrief 


class TaskStatus(str, Enum):
    """Status of a task in the plan"""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class TaskType(str, Enum):
    """Types of CAD operations"""
    CREATE_SOLID = "create_solid"
    CREATE_SKETCH = "create_sketch"
    BOOLEAN_UNION = "boolean_union"
    BOOLEAN_SUBTRACT = "boolean_subtract"
    BOOLEAN_INTERSECT = "boolean_intersect"
    ADD_HOLE = "add_hole"
    ADD_FILLET = "add_fillet"
    ADD_CHAMFER = "add_chamfer"
    TRANSFORM = "transform"
    MIRROR = "mirror"
    PATTERN = "pattern"
    EXTRUDE = "extrude"
    REVOLVE = "revolve"


class DesignTask(BaseModel):
    """Individual task in the construction plan"""
    task_id: str = Field(..., description="Unique task identifier")
    step_number: int = Field(..., description="Sequential step number")
    task_type: TaskType = Field(..., description="Type of CAD operation")
    description: str = Field(..., description="Human-readable task description")
    
    # Technical Specifications
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Task parameters")
    dependencies: List[str] = Field(default_factory=list, description="IDs of prerequisite tasks")
    target_features: List[str] = Field(default_factory=list, description="Feature IDs from DesignBrief")
    
    # Execution Tracking (FIXED: Explicit default=None)
    status: TaskStatus = Field(default=TaskStatus.PENDING)
    generated_code: Optional[str] = Field(default=None, description="CadQuery code generated by DA")
    verification_result: Optional[Dict[str, Any]] = Field(default=None, description="QAV verification result")
    attempts: int = Field(default=0, description="Number of generation attempts")
    error_history: List[str] = Field(default_factory=list, description="Errors encountered")
    
    # Timestamps (FIXED: Explicit default=None)
    started_at: Optional[datetime] = Field(default=None)
    completed_at: Optional[datetime] = Field(default=None)

    metadata: Dict[str, Any] = Field(default_factory=dict, description="Performance metrics and extras")


class ConstructionPlan(BaseModel):
    """
    Complete construction plan for a design
    Output of Phase 2: Project Manager
    """
    plan_id: str = Field(..., description="Unique plan identifier")
    design_brief_id: str = Field(..., description="Reference to source DesignBrief")
    timestamp: datetime = Field(default_factory=datetime.now)
    
    # Planning Strategy
    strategy: Union[str, List[str]] = Field(..., description="High-level construction strategy") 
    
    reasoning: str = Field(..., description="PM's reasoning for this approach")
    retrieved_patterns: List[str] = Field(
        default_factory=list,
        description="EDR patterns used for planning"
    )
    
    # Task Sequence
    tasks: List[DesignTask] = Field(default_factory=list)
    
    # Execution State
    current_task_index: int = Field(default=0)
    is_completed: bool = Field(default=False)
    total_attempts: int = Field(default=0)
    
    # Metadata
    estimated_complexity: Optional[str] = Field(default=None, description="low, medium, high")
    tags: List[str] = Field(default_factory=list)
    
    def get_next_task(self) -> Optional[DesignTask]:
        """Get the next pending task"""
        if self.current_task_index < len(self.tasks):
            return self.tasks[self.current_task_index]
        return None
    

    @field_validator('strategy', mode='before')
    def parse_strategy(cls, v):
        """Auto-fix if LLM returns a list instead of a string"""
        if isinstance(v, list):
            return " ".join(str(i) for i in v)
        return v
    
    
    def mark_task_completed(self, task_id: str, code: str, verification: Dict[str, Any]) -> None:
        """Mark a task as completed with its results"""
        for task in self.tasks:
            if task.task_id == task_id:
                task.status = TaskStatus.COMPLETED
                task.generated_code = code
                task.verification_result = verification
                task.completed_at = datetime.now()
                break
        self.current_task_index += 1
    
    def mark_task_failed(self, task_id: str, error: str) -> None:
        """Mark a task as failed and record the error"""
        for task in self.tasks:
            if task.task_id == task_id:
                task.status = TaskStatus.FAILED
                task.error_history.append(error)
                task.attempts += 1
                break
    
    def get_task_by_id(self, task_id: str) -> Optional[DesignTask]:
        """Retrieve a specific task by ID"""
        for task in self.tasks:
            if task.task_id == task_id:
                return task
        return None
    
    def get_completed_code(self) -> str:
        """Combine all completed task code into final script"""
        code_blocks = []
        code_blocks.append("import cadquery as cq")
        code_blocks.append("")
        
        for task in self.tasks:
            if task.status == TaskStatus.COMPLETED and task.generated_code:
                code_blocks.append(f"# Step {task.step_number}: {task.description}")
                code_blocks.append(task.generated_code)
                code_blocks.append("")
        
        return "\n".join(code_blocks)
    
    def to_json_file(self, filepath: str) -> None:
        """Export plan to JSON file"""
        with open(filepath, 'w') as f:
            f.write(self.model_dump_json(indent=2))
    
    @classmethod
    def from_json_file(cls, filepath: str) -> 'ConstructionPlan':
        """Load plan from JSON file"""
        with open(filepath, 'r') as f:
            return cls.model_validate_json(f.read())